DELIMITER $$
SET GLOBAL EVENT_SCHEDULER=ON$$
CREATE	EVENT `dev`.`EV_UPDATE_SCHEDULE`

ON SCHEDULE EVERY 1 DAY 

DO
	BEGIN
	    UPDATE item_schedules SET REMAINING_QUANTITY=100 WHERE FOOD_TYPE_ID=1;
	    UPDATE item_schedules SET REMAINING_QUANTITY=75 WHERE FOOD_TYPE_ID=2;
	    UPDATE item_schedules SET REMAINING_QUANTITY=200 WHERE FOOD_TYPE_ID=3;
	    UPDATE item_schedules SET REMAINING_QUANTITY=100 WHERE FOOD_TYPE_ID=4;
	    TRUNCATE TABLE ORDER_RECORDS; 
	END$$

DELIMITER ;
