DELIMITER $$

CREATE PROCEDURE PR_ORDER_RECORD(IN SEATNUM VARCHAR(10),IN  ITEM_LIST MEDIUMTEXT,IN QTY_LIST MEDIUMTEXT)
 BEGIN
DECLARE ITEM TEXT DEFAULT NULL ;
DECLARE ITEM_LENGTH INT DEFAULT NULL;
DECLARE NEXT_ITEM TEXT DEFAULT NULL;        
DECLARE QTY TEXT DEFAULT NULL ;         
DECLARE QTY_LENGTH INT DEFAULT NULL;        
DECLARE NEXT_QTY TEXT DEFAULT NULL;
DECLARE RANDOM_ORDER_ID INT;

SET RANDOM_ORDER_ID=(FLOOR(100+RAND()*(100)));
iterator :
 LOOP            
IF LENGTH(TRIM(ITEM_LIST)) = 0 OR ITEM_LIST IS NULL OR LENGTH(TRIM(QTY_LIST)) = 0 OR QTY_LIST IS NULL THEN
LEAVE iterator;
END IF;
               
SET ITEM = SUBSTRING_INDEX(ITEM_LIST,',',1);
SET ITEM_LENGTH = LENGTH(ITEM);             
SET NEXT_ITEM = TRIM(ITEM);
                                 
SET QTY = SUBSTRING_INDEX(QTY_LIST,',',1);                
SET QTY_LENGTH = LENGTH(QTY);
SET NEXT_QTY = TRIM(QTY);
                                  
CALL PR_FOOD_ORDER(RANDOM_ORDER_ID,ITEM,SEATNUM,QTY);
                                
SET ITEM_LIST = INSERT(ITEM_LIST,1,ITEM_LENGTH + 1,'');              
SET QTY_LIST = INSERT(QTY_LIST,1,QTY_LENGTH + 1,'');
END LOOP;
SELECT SUM(PRICE) FROM BILL_DETAIL WHERE ORDER_ID=RANDOM_ORDER_ID;
IF (SELECT COUNT(STATUS)FROM ORDER_RECORDS WHERE ORDER_ID=RANDOM_ORDER_ID AND STATUS='ORDERED')<>0 THEN
UPDATE SEED_SEAT SET STATUS='NOT AVAILABLE' WHERE SEATNO=SEATNUM;
END IF;
    END$$

DELIMITER ;

