-- FOR CANCELL MORE THAN ONE ORDER
DELIMITER $$
CREATE PROCEDURE PR_CANCEL_ORDERS(IN ORDERED_ID INT,IN  ITEM_LIST MEDIUMTEXT)
BEGIN
DECLARE ITEMS_NAME TEXT DEFAULT NULL ;
DECLARE ITEM_LENGTH INT DEFAULT NULL;
DECLARE NEXT_ITEM TEXT DEFAULT NULL;        
DECLARE SEATNUM VARCHAR(60);
        
iterator :    
LOOP            
IF LENGTH(TRIM(ITEM_LIST)) = 0 OR ITEM_LIST IS NULL  THEN
LEAVE iterator;
END IF;
               
SET ITEMS_NAME = SUBSTRING_INDEX(ITEM_LIST,',',1);
SET ITEM_LENGTH = LENGTH(ITEMS_NAME);             
SET NEXT_ITEM = TRIM(ITEMS_NAME);
 /*TO CALL SINGLE ORDER CANCEL PROCEDURE*/                                 
CALL PR_CANCEL_ORDER(ORDERED_ID,ITEMS_NAME);
                               
SET ITEM_LIST = INSERT(ITEM_LIST,1,ITEM_LENGTH + 1,'');              
END LOOP;
SELECT SUM(PRICE) FROM BILL_DETAIL WHERE ORDER_ID=ORDERED_ID;
IF (SELECT COUNT(STATUS)FROM ORDER_RECORDS WHERE ORDER_ID=ORDERED_ID AND STATUS='ORDERED')=0 THEN
SELECT SEATNO INTO SEATNUM FROM ORDER_RECORDS WHERE ORDER_ID=ORDERED_ID AND ITEM=ITEMS_NAME; 
UPDATE SEED_SEAT SET STATUS='AVAILABLE' WHERE SEATNO=SEATNUM;
END IF;
    END$$

DELIMITER ;
