-- FOR CANCELLING ORDER
DELIMITER $$

CREATE  PROCEDURE PR_CANCEL_ORDER(IN ORDERED_ID INT,IN ITEMS_NAME VARCHAR(90))
BEGIN
        DECLARE status_ VARCHAR(20);
        DECLARE QTY INT;
        DECLARE SEATNUM VARCHAR(60);
	SELECT STATUS INTO STATUS_ FROM ORDER_RECORDS WHERE ORDER_ID=ORDERED_ID AND ITEM=ITEMS_NAME; 
	
	IF (status_='ORDERED')THEN
	SELECT QUANTITY INTO QTY FROM ORDER_RECORDS WHERE ORDER_ID=ORDERED_ID AND ITEM=ITEMS_NAME ;
	SELECT SEATNO INTO SEATNUM FROM ORDER_RECORDS WHERE ORDER_ID=ORDERED_ID AND ITEM=ITEMS_NAME; 

              UPDATE ORDER_RECORDS SET ORDER_RECORDS.`STATUS`  ='CANCELLED' WHERE ORDER_ID=ORDERED_ID AND ITEM=ITEMS_NAME;
              UPDATE ITEM_SCHEDULES SET item_schedules.`REMAINING_QUANTITY`=REMAINING_QUANTITY+QTY WHERE ITEM_NAME=ITEMS_NAME 
              AND (SELECT FN_GET_SESSIONID()=FOOD_TYPE_ID);
              DELETE FROM BILL_DETAIL  WHERE ORDER_ID=ORDERED_ID AND ITEM=ITEMS_NAME;
              SELECT 'ORDER CANCELLED' AS STATEMENT;
              END IF;
              IF (STATUS_='BILL PAID') THEN
	      SELECT 'PAID ORDER CANNOT BE CANCEL' AS STATEMENT;
	      END IF;
	      IF (STATUS_='CANCELLED') THEN
	      SELECT 'YOUR ORDER ALREADY CANCELLED';
              END IF;
              
	END$$

DELIMITER ;

/* FOR BILL_DETAILS*/

DELIMITER //
CREATE PROCEDURE PR_BILL_DETAILS(IN ORDERED_ID INT,IN ITEMS_NAME VARCHAR(70))
BEGIN
DECLARE status_ VARCHAR(20);
DECLARE SEATNUM VARCHAR(60);
	SELECT STATUS INTO STATUS_ FROM ORDER_RECORDS WHERE ORDER_ID=ORDERED_ID AND ITEM=ITEMS_NAME ; 
	SELECT SEATNO INTO SEATNUM FROM ORDER_RECORDS WHERE ORDER_ID=ORDERED_ID AND ITEM=ITEMS_NAME; 
IF (status_='ORDERED')THEN
        UPDATE ORDER_RECORDS SET STATUS  ='BILL PAID ' WHERE ORDER_ID=ORDERED_ID AND ITEM=ITEMS_NAME;
        DELETE FROM BILL_DETAIL  WHERE ORDER_ID=ORDERED_ID AND ITEM=ITEMS_NAME;
	SELECT 'YOUR BILL IS PAID' AS STATEMENT;
  END IF;
  IF (STATUS_='CANCELLED') THEN
	SELECT 'YOUR ORDER CANCELLED SO NO NEED TO PAY' AS MESSAGE;
  END IF;
  IF (STATUS_='BILL PAID') THEN
	SELECT 'YOUR BILL ALREADY PAID' AS MESSAGE;
  END IF;
         
END //
